// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureLoginSystem.Data;

#nullable disable

namespace SecureLoginSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511120444_AddCreditCardFieldsAndSeedUsers")]
    partial class AddCreditCardFieldsAndSeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureLoginSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsraeliId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreditCardNumber = "1234 5567 8901 2345",
                            Cvc = "123",
                            FirstName = "Israeli",
                            IsraeliId = "123456789",
                            LastName = "Israeili",
                            PasswordHash = "A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=",
                            Role = "Admin",
                            Username = "admin",
                            ValidDate = "12/32"
                        },
                        new
                        {
                            Id = 2,
                            CreditCardNumber = "1111 2222 3333 4444",
                            Cvc = "111",
                            FirstName = "David",
                            IsraeliId = "111222333",
                            LastName = "Cohen",
                            PasswordHash = "D/4avRoIIVNTwjPW4AlhPpXuxCU4Mqdhryj/N6xaFQw=",
                            Role = "User",
                            Username = "user1",
                            ValidDate = "11/30"
                        },
                        new
                        {
                            Id = 3,
                            CreditCardNumber = "2222 3333 4444 5555",
                            Cvc = "222",
                            FirstName = "Noa",
                            IsraeliId = "222333444",
                            LastName = "Levi",
                            PasswordHash = "7e4p+IJUO5VmILJtDuDn6VA5mxxCIvXeBeBkJbTJlek=",
                            Role = "User",
                            Username = "user2",
                            ValidDate = "10/31"
                        },
                        new
                        {
                            Id = 4,
                            CreditCardNumber = "3333 4444 5555 6666",
                            Cvc = "333",
                            FirstName = "Yossi",
                            IsraeliId = "333444555",
                            LastName = "Mizrahi",
                            PasswordHash = "MYruP+2MnQQNNaf8H6d2+zEwODOqLeiFNU3fPUTY+2k=",
                            Role = "User",
                            Username = "user3",
                            ValidDate = "09/29"
                        },
                        new
                        {
                            Id = 5,
                            CreditCardNumber = "4444 5555 6666 7777",
                            Cvc = "444",
                            FirstName = "Maya",
                            IsraeliId = "444555666",
                            LastName = "Peretz",
                            PasswordHash = "efBvj94zNGFznyIAkKI8sqefbXFL7hANDktK8kkpRhk=",
                            Role = "User",
                            Username = "user4",
                            ValidDate = "08/28"
                        },
                        new
                        {
                            Id = 6,
                            CreditCardNumber = "5555 6666 7777 8888",
                            Cvc = "555",
                            FirstName = "Omer",
                            IsraeliId = "555666777",
                            LastName = "Biton",
                            PasswordHash = "wfMw0K/zHByHQD8eQ0e8whr/fBeZCHI1NfKzFyNwJSU=",
                            Role = "User",
                            Username = "user5",
                            ValidDate = "07/30"
                        },
                        new
                        {
                            Id = 7,
                            CreditCardNumber = "6666 7777 8888 9999",
                            Cvc = "666",
                            FirstName = "Dana",
                            IsraeliId = "666777888",
                            LastName = "Avraham",
                            PasswordHash = "12l1cEYvdWK4PoEljeDx5Bgy6YBy5Ew27I7+xGeG4k4=",
                            Role = "User",
                            Username = "user6",
                            ValidDate = "06/31"
                        },
                        new
                        {
                            Id = 8,
                            CreditCardNumber = "7777 8888 9999 0000",
                            Cvc = "777",
                            FirstName = "Eli",
                            IsraeliId = "777888999",
                            LastName = "Shalom",
                            PasswordHash = "QcmR62pmJCwEVBkSRCeBg85Yz0przTcveZ5LnMAYhq8=",
                            Role = "User",
                            Username = "user7",
                            ValidDate = "05/29"
                        },
                        new
                        {
                            Id = 9,
                            CreditCardNumber = "8888 9999 0000 1111",
                            Cvc = "888",
                            FirstName = "Roni",
                            IsraeliId = "888999000",
                            LastName = "Malka",
                            PasswordHash = "KSaicx9LMSwImCys+AYesUv2XBqHzF1w6GTgecYiBzE=",
                            Role = "User",
                            Username = "user8",
                            ValidDate = "04/30"
                        },
                        new
                        {
                            Id = 10,
                            CreditCardNumber = "9999 0000 1111 2222",
                            Cvc = "999",
                            FirstName = "Tamar",
                            IsraeliId = "999000111",
                            LastName = "Azulai",
                            PasswordHash = "iI3yWuNXckJKVgxxUqHeeURA4Opc/uYoKDM6RWpQbgU=",
                            Role = "User",
                            Username = "user9",
                            ValidDate = "03/31"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
